name: Build Documentation

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Sphinx>3.1 matplotlib
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          sudo apt-get --yes update
          sudo apt-get --yes install texlive-latex-base
          sudo apt-get --yes install texlive-fonts-recommended
          sudo apt-get --yes install texlive-fonts-extra
          sudo apt-get --yes install texlive-latex-extra
          sudo apt-get --yes install texlive-science
          sudo apt-get --yes install texlive-extra-utils
      - name: Build HTML
        run: |
          python setup.py build_sphinx -b html
      - name: Build PDF
        run: |
          python setup.py build_sphinx -b latex
          make latexpdf
      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: |
            build/sphinx/html
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
